"""test

Revision ID: 372de84036eb
Revises: 
Create Date: 2023-09-12 18:08:58.689689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372de84036eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_plugin',
    sa.Column('id', sa.Integer(), nullable=False, comment='autoincrement id'),
    sa.Column('tenant', sa.String(), nullable=True, comment="user's tenant"),
    sa.Column('user_code', sa.String(), nullable=True, comment='user code'),
    sa.Column('user_name', sa.String(), nullable=True, comment='user name'),
    sa.Column('name', sa.String(), nullable=False, comment='plugin name'),
    sa.Column('type', sa.String(), nullable=True, comment='plugin type'),
    sa.Column('version', sa.String(), nullable=True, comment='plugin version'),
    sa.Column('use_count', sa.Integer(), nullable=True, comment='plugin total use count'),
    sa.Column('succ_count', sa.Integer(), nullable=True, comment='plugin total success count'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='plugin install time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uk_name')
    )
    op.create_table('plugin_hub',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='autoincrement id'),
    sa.Column('name', sa.String(), nullable=False, comment='plugin name'),
    sa.Column('author', sa.String(), nullable=True, comment='plugin author'),
    sa.Column('email', sa.String(), nullable=True, comment='plugin author email'),
    sa.Column('type', sa.String(), nullable=True, comment='plugin type'),
    sa.Column('version', sa.String(), nullable=True, comment='plugin version'),
    sa.Column('storage_channel', sa.String(), nullable=True, comment='plugin storage channel'),
    sa.Column('storage_url', sa.String(), nullable=True, comment='plugin download url'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='plugin upload time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uk_name')
    )
    with op.batch_alter_table('plugin_hub', schema=None) as batch_op:
        batch_op.create_index('idx_q_type', ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin_hub', schema=None) as batch_op:
        batch_op.drop_index('idx_q_type')

    op.drop_table('plugin_hub')
    op.drop_table('my_plugin')
    # ### end Alembic commands ###
