"""test

Revision ID: 800e0edbf9fc
Revises: 372de84036eb
Create Date: 2023-09-13 16:19:32.434194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800e0edbf9fc'
down_revision: Union[str, None] = '372de84036eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_plugin', schema=None) as batch_op:
        batch_op.create_unique_constraint('uk_name', ['name'])

    with op.batch_alter_table('plugin_hub', schema=None) as batch_op:
        batch_op.create_unique_constraint('uk_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin_hub', schema=None) as batch_op:
        batch_op.drop_constraint('uk_name', type_='unique')

    with op.batch_alter_table('my_plugin', schema=None) as batch_op:
        batch_op.drop_constraint('uk_name', type_='unique')

    # ### end Alembic commands ###
